// Blog catalog — mirrored from TraderDynamiq's article structure for the contract spec.
// Article bodies are placeholders; titles, slugs, excerpts, and categories are real.

export interface BlogArticle {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
}

export const BLOG_ARTICLES: BlogArticle[] = [
  { slug: 'traderdynamiq-launch-announcement', title: 'Introducing TraderDynamiq', excerpt: 'TraderDynamiq is now live. Upload your trades from 67+ brokers and get an automated breakdown of every costly pattern.', category: 'Product Launch' },
  { slug: 'tradezella-alternatives', title: '5 Best TradeZella Alternatives in 2026', excerpt: 'Looking for a TradeZella alternative? Compare TraderDynamiq, Tradervue, Edgewonk and more.', category: 'Comparisons' },
  { slug: 'overtrading-silent-account-killer', title: 'Overtrading: The Silent Account Killer', excerpt: 'Overtrading destroys more trading accounts than bad strategy. Learn the 7 warning signs.', category: 'Psychology' },
  { slug: 'how-to-analyze-trading-performance', title: 'How to Analyze Your Trading Performance', excerpt: 'Most traders track P&L and nothing else. Learn a complete performance analysis framework.', category: 'Performance Analysis' },
  { slug: 'tradervue-alternatives', title: '6 Best Tradervue Alternatives in 2026', excerpt: 'Looking for a Tradervue alternative? Compare TraderDynamiq, Edgewonk, TradeZella.', category: 'Comparisons' },
  { slug: 'best-trading-journal-day-traders-2026', title: 'Best Trading Journal for Day Traders in 2026', excerpt: 'We compared 5 trading journal apps for day traders in 2026. Pricing, features, broker support.', category: 'Tools / Reviews' },
  { slug: 'traderdynamiq-review-2026', title: 'TraderDynamiq Review 2026', excerpt: 'In-depth TraderDynamiq review for 2026. Features, pricing, pros, cons, and who it’s for.', category: 'Product Review' },
  { slug: 'trading-journal-spreadsheet-vs-software', title: 'Trading Journal Spreadsheet vs Software', excerpt: 'Should you journal in a spreadsheet or use dedicated software? We compare setup, scale, accuracy.', category: 'Tools / Strategy' },
  { slug: 'best-trading-journal-for-beginners', title: 'Best Trading Journal for Beginners (2026)', excerpt: 'New to trade journaling? This beginner-friendly guide covers what to track, which app fits you.', category: 'Beginner Guide' },
  { slug: 'tradersync-alternatives', title: '6 Best TraderSync Alternatives in 2026', excerpt: 'Looking for a TraderSync alternative? Compare TraderDynamiq, Tradervue, Edgewonk.', category: 'Comparisons' },
  { slug: 'trading-rules-playbook', title: 'Trading Rules That Actually Work', excerpt: 'Learn how to build a personal trading playbook with rules that actually improve outcomes.', category: 'Strategy' },
  { slug: 'trading-performance-analysis-guide', title: 'How to Analyze Your Trading Performance (Guide)', excerpt: 'Learn how to analyze your trading performance beyond win rate. This guide covers everything.', category: 'Performance Analysis' },
  { slug: 'edgewonk-alternatives', title: '6 Best Edgewonk Alternatives in 2026', excerpt: 'Looking for an Edgewonk alternative? Compare TraderDynamiq, Tradervue, TradeZella.', category: 'Comparisons' },
  { slug: 'trading-mistakes-cost-analysis', title: 'How Much Do Trading Mistakes Cost?', excerpt: 'Data analysis of the 4 costliest trading mistakes — revenge trading, overtrading, FOMO, tilt.', category: 'Data Analysis' },
  { slug: 'best-trading-journal-day-traders', title: 'Best Trading Journal for Day Traders (2026)', excerpt: 'Compare the best trading journals for day traders in 2026. Side-by-side features.', category: 'Tools / Reviews' },
  { slug: 'trading-journal-vs-spreadsheet', title: 'Trading Journal vs Spreadsheet', excerpt: 'Still tracking trades in Excel? Here’s what spreadsheets can’t do — pattern detection.', category: 'Tools / Strategy' },
  { slug: 'trading-psychology-tools', title: 'Trading Psychology Tools', excerpt: 'Review of tools and software that help traders manage psychology and detect behavioral patterns.', category: 'Psychology / Tools' },
  { slug: 'free-trading-journal', title: 'Free Trading Journal', excerpt: 'Looking for a free trading journal? Here’s an honest breakdown of what free options actually cover.', category: 'Tools / Reviews' },
  { slug: 'how-to-journal-trades-effectively', title: 'How to Journal Trades Effectively', excerpt: 'Learn the exact process for keeping an effective trading journal. Beyond recording prices.', category: 'Journaling Guide' },
  { slug: 'how-much-do-trading-mistakes-cost', title: 'How Much Do Trading Mistakes Actually Cost?', excerpt: 'Trading mistakes cost active traders $40,000–100,000+ per year. See the real numbers.', category: 'Data Analysis' },
  { slug: 'trading-journal-template-2026', title: 'Trading Journal Template 2026', excerpt: 'The complete trading journal template for 2026. Every field to track, how to track it.', category: 'Templates' },
  { slug: 'best-trading-journal-apps-compared', title: 'Best Trading Journal Apps Compared (2026)', excerpt: 'Comparing the best trading journal apps in 2026? Honest, detailed review.', category: 'Tools / Reviews' },
  { slug: 'crypto-trading-mistakes-beginners', title: '12 Crypto Trading Mistakes Every Beginner Makes', excerpt: 'Avoid the most costly crypto trading mistakes. From overleveraging to revenge trading.', category: 'Crypto / Beginner' },
  { slug: 'how-to-stop-revenge-trading', title: 'How to Stop Revenge Trading', excerpt: 'Revenge trading costs the average active trader $400-$1,200 per month. Here’s how to stop.', category: 'Psychology / Strategy' },
  { slug: 'traderdynamiq-vs-trademetria', title: 'TraderDynamiq vs TradeMetria', excerpt: 'Compare TraderDynamiq and TradeMetria head-to-head. Behavioral analytics vs general journaling.', category: 'Comparisons' },
  { slug: 'best-trading-journal-alternatives', title: 'Best Trading Journal Alternatives in 2026', excerpt: 'Looking for a better trading journal? Compare TraderDynamiq, Tradervue, TradeZella.', category: 'Comparisons' },
  { slug: 'traderdynamiq-vs-myfxbook', title: 'TraderDynamiq vs Myfxbook', excerpt: 'Comparing TraderDynamiq and Myfxbook: behavioral analytics vs social trading & verification.', category: 'Comparisons' },
  { slug: 'import-trades-from-any-broker', title: 'How to Import Trades from Any Broker', excerpt: 'Step-by-step guide to importing trades from Binance, Bybit, MetaTrader, Interactive Brokers and more.', category: 'How-to / Integration' },
  { slug: 'how-to-become-profitable-trader', title: 'How to Become a Profitable Trader', excerpt: 'Most traders fail because they can’t see their own patterns. Learn the data-driven path to profitability.', category: 'Strategy / Growth' },
  { slug: 'trading-mistakes-beginners-make', title: '7 Trading Mistakes Every Beginner Makes', excerpt: 'The 7 most common beginner trading mistakes and what each one actually costs you.', category: 'Beginner / Data' },
  { slug: 'trading-journal-for-indian-traders', title: 'Best Trading Journal for Indian Traders', excerpt: 'The best trading journal for Indian stock, futures, and options traders. Import from Zerodha, Upstox.', category: 'Regional / Tools' },
  { slug: 'backtesting-vs-forward-testing', title: 'Backtesting vs Forward Testing', excerpt: 'Most backtested strategies fail in live trading. Learn why backtesting overpromises.', category: 'Strategy / Testing' },
  { slug: 'trading-scalping-guide', title: 'Scalping Strategy Guide', excerpt: 'Scalping looks simple — fast trades, small profits. The data tells a different story.', category: 'Strategy / Data' },
  { slug: 'backtesting-trading-strategy', title: 'How to Backtest a Trading Strategy', excerpt: 'Learn how to backtest trading strategies properly. Covers forward testing and out-of-sample.', category: 'Strategy / Guide' },
  { slug: 'trading-risk-management-guide', title: 'Trading Risk Management', excerpt: 'A practical risk management guide for traders. Position sizing, stop-loss placement, exposure caps.', category: 'Risk Management' },
  { slug: 'scalping-performance-analytics', title: 'Scalping Performance Analytics', excerpt: 'Scalping demands different analytics than swing trading. Learn which metrics matter.', category: 'Analytics / Strategy' },
  { slug: 'emotional-trading-cost', title: 'The Real Cost of Emotional Trading', excerpt: 'Emotional trading costs the average active trader 20-40% of potential profits.', category: 'Psychology / Cost' },
  { slug: 'how-much-money-day-traders-lose', title: 'How Much Money Do Day Traders Actually Lose?', excerpt: 'Research shows 70-90% of day traders lose money. We break down the actual data.', category: 'Data Analysis' },
  { slug: 'scalping-strategy-data-analysis', title: 'Scalping Strategy Analysis', excerpt: 'Data analysis of scalping strategies. How transaction costs and win rate requirements stack up.', category: 'Analytics / Strategy' },
  { slug: 'trading-journal-for-options', title: 'Options Trading Journal', excerpt: 'Options trading requires tracking strategy type, Greeks, expiration dates, and underlying.', category: 'Options / Journaling' },
  { slug: 'trading-journal-for-swing-traders', title: 'Trading Journal for Swing Traders', excerpt: 'Swing traders need different journaling than day traders. Learn how to track multi-day positions.', category: 'Swing Trading' },
  { slug: 'trading-journal-for-options-traders', title: 'Trading Journal for Options Traders', excerpt: 'Options journals need to track Greeks, strategy type, expirations, and adjustments.', category: 'Options / Journaling' },
  { slug: 'import-metatrader-trades', title: 'How to Import MetaTrader Trades', excerpt: 'Learn how to export your MT4 or MT5 trade history and import it into TraderDynamiq.', category: 'How-to / Forex' },
  { slug: 'traderdynamiq-vs-tradersync', title: 'TraderDynamiq vs TraderSync', excerpt: 'Detailed comparison of TraderDynamiq vs TraderSync. See how they differ on detection.', category: 'Comparisons' },
  { slug: 'trading-journal-roi', title: 'Is a Trading Journal Worth It?', excerpt: 'Does keeping a trading journal actually improve results? Data analysis of journaling traders.', category: 'ROI / Strategy' },
  { slug: 'traderdynamiq-vs-edgewonk', title: 'TraderDynamiq vs Edgewonk', excerpt: 'TraderDynamiq vs Edgewonk: side-by-side comparison of features, pricing, broker support.', category: 'Comparisons' },
  { slug: 'trading-psychology-emotions', title: 'Trading Psychology: How Emotions Destroy Your Edge', excerpt: 'Fear, greed, FOMO, and revenge are predictable patterns in your trading data.', category: 'Psychology' },
  { slug: 'trading-tilt-explained', title: 'Trading Tilt Explained', excerpt: 'Trading tilt costs more than bad setups. Learn how tilt shows up in your trade data.', category: 'Psychology' },
  { slug: 'trading-journal-for-futures-traders', title: 'Trading Journal for Futures Traders', excerpt: 'Futures traders need a journal that handles tick-based P&L and session timing.', category: 'Futures / Journaling' },
  { slug: 'trading-journal-for-stocks', title: 'Best Trading Journal for Stocks', excerpt: 'The best stock trading journals go beyond a spreadsheet. Import from IBKR, TD Ameritrade, ETrade.', category: 'Stocks / Journaling' },
  { slug: 'trading-after-winning-streak', title: 'Why Traders Blow Up After Winning Streaks', excerpt: 'Winning streaks are the most dangerous time in trading. Data shows traders increase size at the worst moment.', category: 'Psychology / Risk' },
  { slug: 'trading-journal-vs-behavioral-analytics', title: 'Trading Journal vs Behavioral Analytics', excerpt: 'A trading journal logs what happened. Behavioral analytics tells you why it keeps happening.', category: 'Analytics / Journaling' },
  { slug: 'trading-journal-api-integration', title: 'How API Integration Makes Trading Journals Useful', excerpt: 'Manual trade logging kills journal consistency. Learn how API integration auto-imports.', category: 'Integration / Tools' },
  { slug: 'trading-expectancy-explained', title: 'Trading Expectancy Explained', excerpt: 'Trading expectancy tells you how much you can expect to make per trade on average.', category: 'Metrics / Education' },
  { slug: 'maximum-drawdown-explained', title: 'Maximum Drawdown Explained', excerpt: 'Maximum drawdown (MDD) measures your worst peak-to-trough decline. Learn why it matters more than ROI.', category: 'Metrics / Risk' },
  { slug: 'trading-accountability-partner', title: 'Your Trading Accountability Partner', excerpt: 'Willpower fails under pressure. Automated accountability doesn’t.', category: 'Psychology / Tools' },
  { slug: 'trading-discipline-tracker', title: 'How to Actually Track Trading Discipline', excerpt: 'Your P&L tells you results. Discipline tracking tells you process quality.', category: 'Metrics / Discipline' },
  { slug: 'risk-reward-ratio-explained', title: 'Risk-Reward Ratio Explained', excerpt: 'Risk-reward ratio is the most misunderstood metric in trading. Learn what it really means.', category: 'Metrics / Education' },
  { slug: 'trading-slippage-explained', title: 'Trading Slippage Explained', excerpt: 'Slippage adds hidden cost to every market order. Learn how to measure slippage in your data.', category: 'Costs / Metrics' },
  { slug: 'automated-trading-journal', title: 'Automated Trading Journal', excerpt: 'Stop manually logging trades. An automated trading journal imports your history end-to-end.', category: 'Automation / Tools' },
  { slug: 'best-trading-journal-app', title: 'Best Trading Journal App in 2026', excerpt: 'Comparing trading journal apps in 2026? Here’s what separates useful tools from data graveyards.', category: 'Tools / Reviews' },
  { slug: 'trading-journal-spreadsheet-limits', title: 'Why Your Trading Journal Spreadsheet Isn’t Working', excerpt: 'Excel and Google Sheets trading journals fail for 3 specific reasons.', category: 'Tools / Limitations' },
  { slug: 'leverage-risk-trading', title: 'Trading Leverage Explained', excerpt: 'Leverage amplifies both profits and losses, but the math isn’t symmetric.', category: 'Risk / Education' },
  { slug: 'forex-trading-journal', title: 'Best Trading Journal for Forex Traders', excerpt: 'Find the best trading journal for forex. Import from MetaTrader 4, MetaTrader 5, cTrader.', category: 'Forex / Journaling' },
  { slug: 'trading-journal-excel-vs-software', title: 'Excel Trading Journal vs Dedicated Software', excerpt: 'Comparing Excel/Google Sheets journals against dedicated software. When each one wins.', category: 'Tools / Comparison' },
  { slug: 'trading-consistency', title: 'Trading Consistency', excerpt: 'Consistent trading isn’t about winning every day. It’s about making sure your bad days don’t blow up.', category: 'Psychology / Performance' },
  { slug: 'prop-firm-trading-journal', title: 'Trading Journal for Prop Firm Traders', excerpt: 'The best trading journal for prop firm traders. Import from FTMO, TopstepX, MyForexFunds.', category: 'Prop Trading' },
  { slug: 'paper-trading-vs-live', title: 'Paper Trading vs Live Trading', excerpt: 'Paper trading builds mechanics, but live trading adds emotions that change everything.', category: 'Strategy / Education' },
  { slug: 'trading-journal-for-scalpers', title: 'Scalping Journal', excerpt: 'Scalpers can’t manually review 50+ trades daily. Learn how automated analysis saves time.', category: 'Scalping / Journaling' },
  { slug: 'traderdynamiq-vs-tradervue', title: 'TraderDynamiq vs Tradervue', excerpt: 'Detailed comparison of TraderDynamiq and Tradervue for active traders.', category: 'Comparisons' },
  { slug: 'import-binance-trades', title: 'How to Import Binance Futures Trades', excerpt: 'Step-by-step guide to importing Binance Futures trades. Covers CSV trade history and API.', category: 'Crypto / How-to' },
  { slug: 'trading-plan-template', title: 'Trading Plan Template', excerpt: 'Most trading plans fail because they’re too vague to measure. This template gives you concrete rules.', category: 'Templates / Strategy' },
  { slug: 'trading-drawdown-recovery', title: 'Trading Drawdowns', excerpt: 'Every trader faces drawdowns. What separates survivors from blowups is how they recover.', category: 'Risk / Psychology' },
  { slug: 'worst-trading-hours', title: 'How to Find Your Worst Trading Hours', excerpt: 'Most traders have 2-3 hours that account for the majority of their losses. Learn how to find yours.', category: 'Performance / Analytics' },
  { slug: 'day-trading-mistakes-data', title: 'The 10 Most Expensive Day Trading Mistakes', excerpt: 'These 10 day trading mistakes cost more than any other. Ranked by actual P&L loss.', category: 'Data / Day Trading' },
  { slug: 'how-to-review-trades', title: 'How to Review Your Trades', excerpt: 'Most trade reviews waste time. Learn a 5-step structured trade review process.', category: 'Process / Strategy' },
  { slug: 'loss-streaks-when-to-stop', title: 'Loss Streaks', excerpt: 'Loss streaks are inevitable, but trading through them makes them worse.', category: 'Psychology / Risk' },
  { slug: 'trading-routine-daily-process', title: 'How to Build a Daily Trading Routine', excerpt: 'Most trading routines are vague checklists. Learn how to build a structured daily process.', category: 'Process / Discipline' },
  { slug: 'position-sizing-mistakes', title: 'Position Sizing Mistakes', excerpt: 'Poor position sizing costs traders more than bad entries. Learn the 5 most common mistakes.', category: 'Risk / Strategy' },
  { slug: 'trading-performance-metrics-guide', title: 'The Complete Guide to Trading Performance Metrics', excerpt: 'Go beyond win rate and P&L. Learn 20+ trading performance metrics including expectancy.', category: 'Metrics / Guide' },
  { slug: 'trading-journal-template-spreadsheet', title: 'Free Trading Journal Template vs Automated Analytics', excerpt: 'Free spreadsheet journal templates are popular but rarely lead to improvement.', category: 'Templates / Tools' },
  { slug: 'how-to-stop-losing-money-trading', title: 'How to Stop Losing Money Trading', excerpt: 'Most traders lose money for specific, measurable reasons. Learn the 5 most common ones.', category: 'Strategy / Improvement' },
  { slug: 'trading-journal-review-checklist', title: 'Weekly Trading Review Checklist', excerpt: 'Use this 15-question weekly trading review checklist to find patterns and measure compliance.', category: 'Process / Checklists' },
  { slug: 'fomo-trading-cost', title: 'FOMO Trading', excerpt: 'FOMO trading — entering positions because of fear of missing out — accounts for huge losses.', category: 'Psychology / Cost' },
  { slug: 'trading-loss-streaks', title: 'How to Handle Trading Loss Streaks', excerpt: 'Loss streaks are inevitable. Account blowups are optional. Learn how to set guardrails.', category: 'Risk / Psychology' },
  { slug: 'finding-your-trading-edge', title: 'How to Find Your Trading Edge', excerpt: 'Most traders think they have an edge but can’t prove it with numbers. Here’s how.', category: 'Strategy / Data' },
  { slug: 'average-true-range-atr-trading', title: 'Average True Range (ATR) in Trading', excerpt: 'Learn how ATR measures market volatility and how to use it for position sizing.', category: 'Technical Analysis' },
  { slug: 'win-rate-doesnt-matter', title: 'Why Your Win Rate Doesn’t Matter', excerpt: 'A 40% win rate can be more profitable than 70%. Learn why win rate is misleading on its own.', category: 'Metrics / Education' },
  { slug: 'trading-journal-mistakes-to-avoid', title: '7 Trading Journal Mistakes That Kill Progress', excerpt: 'Most traders journal wrong. Discover the 7 most common trading journal mistakes.', category: 'Journaling / Mistakes' },
  { slug: 'best-trading-journal-2026', title: 'Best Trading Journal Software in 2026', excerpt: 'Compare the best trading journal software in 2026. In-depth review of TraderDynamiq and others.', category: 'Tools / Reviews' },
  { slug: 'overtrading-hidden-cost', title: 'The Hidden Cost of Overtrading', excerpt: 'Overtrading silently destroys trading accounts through fees, poor setups, and emotional fatigue.', category: 'Psychology / Cost' },
  { slug: 'trading-journal-for-day-traders', title: 'Best Trading Journal for Day Traders: Speed, Automation, Pattern Detection', excerpt: 'Day traders need a journal that keeps up with high-frequency execution. Auto-import + pattern detection.', category: 'Day Trading' },
  { slug: 'trading-journal-for-prop-firms', title: 'Trading Journal for Prop Firm Traders: Pass Challenge & Stay Funded', excerpt: 'Prop firm traders need more than trade logs. Learn how behavioral analytics helps you pass.', category: 'Prop Trading' },
  { slug: 'trading-rules-that-work', title: '10 Trading Rules That Actually Work', excerpt: 'Most trading rules fail because nobody tracks them. Here are 10 rules proven by data.', category: 'Rules / Strategy' },
  { slug: 'getting-started-traderdynamiq', title: 'Getting Started with TraderDynamiq', excerpt: 'Step-by-step guide to setting up TraderDynamiq. Import your trades, see your patterns.', category: 'Onboarding' },
  { slug: 'trading-journal-checklist-daily', title: 'Daily Trading Journal Checklist', excerpt: 'A practical 5-minute daily trading review checklist. What to check before, during, after.', category: 'Checklists / Process' },
  { slug: 'trading-fees-hidden-cost', title: 'Trading Fees', excerpt: 'Trading fees silently consume 20-80% of gross profits for active traders. Learn how to measure them.', category: 'Costs / Strategy' },
  { slug: 'trading-drawdown-explained', title: 'Trading Drawdown Explained', excerpt: 'Trading drawdown is the peak-to-trough decline in your account. Learn how to manage it.', category: 'Risk / Metrics' },
  { slug: 'trading-playbook-guide', title: 'How to Build a Trading Playbook', excerpt: 'Most trading rules exist only in your head and break under pressure. Build a written playbook.', category: 'Strategy / Process' },
  { slug: 'sharpe-ratio-trading', title: 'Sharpe Ratio for Traders', excerpt: 'Learn how to calculate and interpret the Sharpe ratio for your trading.', category: 'Metrics / Education' },
  { slug: 'trading-session-analysis', title: 'Trading Session Analysis', excerpt: 'Your trading performance varies dramatically by session. Morning, afternoon, and evening differ.', category: 'Analytics / Performance' },
  { slug: 'how-to-choose-trading-journal', title: 'How to Choose a Trading Journal in 2026', excerpt: 'Picking the wrong trading journal wastes months. This guide covers the 7 features that matter.', category: 'Buyer Guide' },
  { slug: 'trading-tilt-detection', title: 'Trading Tilt: How to Detect It Before It Costs', excerpt: 'Tilt costs traders thousands in preventable losses. Learn the 6 data signatures of tilt.', category: 'Psychology / Detection' },
  { slug: 'symbol-trap-detection', title: 'Symbol Traps', excerpt: 'Some symbols consistently lose you money while others carry your P&L. Learn how to spot the trap symbols.', category: 'Analytics / Strategy' },
  { slug: 'glossary-expectancy', title: 'What Is Trading Expectancy?', excerpt: 'Trading expectancy tells you your average profit per trade. Learn the formula and why it matters.', category: 'Glossary / Education' },
  { slug: 'broker-import-auto-detection', title: '67+ Broker Imports', excerpt: 'TraderDynamiq auto-detects your broker format from CSV uploads. Support for 67+ brokers.', category: 'Integration' },
  { slug: 'best-trading-journal-crypto-futures', title: 'Best Trading Journal for Crypto Futures Traders in 2026', excerpt: 'Compare the best crypto futures trading journals for Binance, Bybit, and OKX.', category: 'Crypto / Tools' },
  { slug: 'traderdynamiq-vs-journalytix', title: 'TraderDynamiq vs Journalytix', excerpt: 'TraderDynamiq vs Journalytix compared: behavioral analytics, broker imports, pricing.', category: 'Comparisons' },
  { slug: 'stop-loss-strategies-data-analysis', title: 'Stop Loss Strategies', excerpt: 'Most stop loss advice is generic. Your actual trade data shows exactly where to place yours.', category: 'Strategy / Data' },
  { slug: 'what-if-simulator-trading', title: 'What-If Simulator', excerpt: 'What if you could delete your worst trading habits from history and see the result?', category: 'Tools / Analysis' },
  { slug: 'why-keep-trading-journal', title: 'Why Keep a Trading Journal?', excerpt: 'The data is clear: traders who journal consistently outperform those who don’t.', category: 'Education' },
  { slug: 'monte-carlo-simulation-trading', title: 'Monte Carlo Simulation for Trading', excerpt: 'Monte Carlo simulation tests whether your trading results come from skill or luck.', category: 'Strategy / Testing' },
  { slug: '50-trading-metrics-every-trader-should-track', title: '50 Trading Metrics Every Trader Should Track', excerpt: 'A comprehensive reference of the 50 most important trading performance metrics.', category: 'Metrics / Reference' },
  { slug: 'trading-psychology-data-approach', title: 'Trading Psychology: A Data-Driven Approach', excerpt: 'Trading psychology isn’t about being disciplined. It’s about measuring your patterns.', category: 'Psychology' },
  { slug: 'glossary-equity-curve', title: 'Equity Curve Explained', excerpt: 'An equity curve shows your cumulative P&L over time. Learn to read yours and spot patterns.', category: 'Glossary / Education' },
  { slug: 'profit-factor-explained', title: 'Profit Factor Explained', excerpt: 'Profit factor is the ratio of gross wins to gross losses. Learn how to calculate and use it.', category: 'Metrics / Education' },
  { slug: 'traderdynamiq-vs-tradezella', title: 'TraderDynamiq vs TradeZella', excerpt: 'Compare TraderDynamiq and TradeZella side-by-side. Behavioral analytics vs general journaling.', category: 'Comparisons' },
  { slug: 'trading-journal-for-forex-traders', title: 'The Complete Forex Trading Journal Guide', excerpt: 'Forex traders need journals built for 24-hour markets. Track performance by session.', category: 'Forex / Guide' },
  { slug: 'trading-journal-for-beginners-2026', title: 'Trading Journal for Beginners: The Complete 2026 Guide', excerpt: 'New to trading journals? This beginner’s guide covers what to track and which apps to consider.', category: 'Beginner / Guide' },
  { slug: 'crypto-trading-journal', title: 'Best Crypto Trading Journal for Bitcoin, Ethereum & Altcoin Traders', excerpt: 'The best crypto trading journal for 2026. Auto-import from Binance, Bybit, OKX.', category: 'Crypto / Tools' },
  { slug: 'revenge-trading-cost', title: 'What Is Revenge Trading?', excerpt: 'Revenge trading costs the average active trader 15-40% of their profits. Here’s the full picture.', category: 'Psychology / Cost' },
];

export const POPULAR_SLUGS = [
  'revenge-trading-cost',
  'overtrading-hidden-cost',
  'worst-trading-hours',
  'trading-journal-vs-behavioral-analytics',
  'best-trading-journal-2026',
  '50-trading-metrics-every-trader-should-track',
];
